afisha:
  places:

    '1.0':
      from: '2013-12-03 00:00'
      to: '2013-12-04 23:00'
      content_type: 'afisha'
      afisha_slug: 'konkurs-uzhin-na-dvoih-ot-funtland'
      replaced_count: 4

    '1.4':
      from: '2013-10-10 00:00'
      to: '2013-01-01 00:00'
      content_type: 'webcam'
      replaced_count: 1

post:
  places:

    '1.0':
      from: '2013-10-30 00:00'
      to: '2014-11-11 00:00'
      content_type: 'post'
      replaced_count: 4

main_page:
  afisha:
    '0':
      from: '2013-11-19 00:00'
      to: '2013-11-23 19:00'
      afisha_slug: 'escobar-grand-opening-atapy-romania'
