afisha:
  places:

    '1.0':
      from: '2014-02-13 14:20'
      to: '2014-02-14 14:20'
      content_type: 'afisha'
      afisha_slug: 'kontsert-ellai-v-nk-fakel-5-marta'
      replaced_count: 4

    '1.4':
      from: '2014-02-07 09:00'
      to: '2014-02-09 09:00'
      content_type: 'afisha'
      afisha_slug: 'bolshoy-detskiy-prazdnik-v-restorane-panda-lounge'
      replaced_count: 1

post:
  places:

    '1.3':
      from: '2013-10-30 00:00'
      to: '2014-11-11 00:00'
      content_type: 'post'
      replaced_count: 4

discount:
  places:
    '1.0':
      from: '2014-01-15 12:30'
      to: '2015-01-16 18:30'
      content_type: 'discount'
      discount_slug: 'podbor-sauny-po-vashemu-zhelaniyu'
      replaced_count: 1
    '1.1':
      from: '2014-01-15 12:30'
      to: '2014-03-13 18:30'
      content_type: 'discount'
      discount_slug: 'kupon-na-valentinku-s-zhivoy-tropicheskoy-babochkoy'
      replaced_count: 1
    '1.2':
      from: '2014-02-13 14:30'
      to: '2014-03-14 14:30'
      content_type: 'discount'
      discount_slug: 'rozygrysh-abonementov-na-mesyats-besplatnyh-zanyatiy-v-fitnes-tsentre-i-podarochnyh-sertifikatov'
      replaced_count: 1

main_page_afisha:
  places:
    '1.0':
      from: '2014-02-13 09:00'
      to: '2014-02-20 09:00'
      content_type: 'afisha'
      afisha_slug: 'letnie-kanikuly-dlya-shkolnikov'
      replaced_count: 1

    '1.2':
      from: '2014-02-13 09:00'
      to: '2014-02-20 09:00'
      content_type: 'afisha'
      afisha_slug: 'letnie-kanikuly-v-ssha'
      replaced_count: 1

    '1.5':
      from: '2014-01-29 14:00'
      to: '2014-02-28 00:00'
      content_type: 'banner'
      title: 'Реклама на футболе'
      image: 'http://storage.znaigorod.ru/files/80822/756-1129/forma_football.jpg'
      link: 'http://www.forma.sibr.ru/football.phtml?p=football&fl=19'
      width: 180
      height: 320

main_page_discounts:
  places:
    '1.0':
      from: '2014-01-15 12:30'
      to: '2015-01-16 18:30'
      content_type: 'discount'
      discount_slug: 'podbor-sauny-po-vashemu-zhelaniyu'
      replaced_count: 1
    '1.3':
      from: '2014-01-15 12:30'
      to: '2014-02-13 18:30'
      content_type: 'discount'
      discount_slug: 'kupon-na-valentinku-s-zhivoy-tropicheskoy-babochkoy'
      replaced_count: 1
