afisha:
  places:

    '1.0':
      from: '2013-12-26 14:30'
      to: '2013-12-30 15:00'
      content_type: 'afisha'
      afisha_slug: 'soberi-druzey-na-novyy-god-v-yorsh-i-poluchi-skidku'
      replaced_count: 4

    '1.4':
      from: '2013-10-10 00:00'
      to: '2013-01-01 00:00'
      content_type: 'webcam'
      replaced_count: 1

post:
  places:

    '1.3':
      from: '2013-10-30 00:00'
      to: '2014-11-11 00:00'
      content_type: 'post'
      replaced_count: 4

main_page:
  afisha:
    '0':
      from: '2014-01-04 16:40'
      to: '2014-01-08 16:40'
      afisha_slug: 'postoyannaya-deystvuyuschaya-vystavka-zhivyh-tropicheskih-babochek-babochkin-dom'
    '1':
      from: '2013-12-12 19:00'
      to: '2013-12-13 19:00'
      afisha_slug: 'kulinarnyy-master-klass-merry-christmas'
  discounts:
    '0':
      from: '2014-01-15 12:30'
      to: '2014-01-16 18:30'
      discount_slug: 'skidki-na-obuchenie-za-rubezhom--2'
