afisha:
  places:

    '1.0':
      from: '2014-01-23 16:40'
      to: '2014-01-25 11:00'
      content_type: 'afisha'
      afisha_slug: 'bm-besplatnyy-otkrytyy-master-klass-biznes-molodosti-kak-sozdat-potok-klientov-v-vash-biznes'
      replaced_count: 1

    '1.1':
      from: '2014-01-24 12:00'
      to: '2014-02-09 12:00'
      content_type: 'afisha'
      afisha_slug: 'planetango-10-v-gosti-k-nam'
      replaced_count: 1

    '1.2':
      from: '2014-01-24 12:00'
      to: '2014-02-08 12:00'
      content_type: 'afisha'
      afisha_slug: 'gala-kontsert-festivalya-planetango-v-gosti-k-nam'
      replaced_count: 1

    '1.3':
      from: '2014-01-25 00:00'
      to: '2014-01-27 00:00'
      content_type: 'afisha'
      afisha_slug: 'kontsert-gruppy-7-rasa'
      replaced_count: 1

    '1.4':
      from: '2013-10-10 00:00'
      to: '2013-01-01 00:00'
      content_type: 'webcam'
      replaced_count: 1

post:
  places:

    '1.3':
      from: '2013-10-30 00:00'
      to: '2014-11-11 00:00'
      content_type: 'post'
      replaced_count: 4

discount:
  places:
    '1.1':
      from: '2013-10-10 00:00'
      to: '2015-01-01 00:00'
      content_type: 'discount'
      discount_slug: 'podbor-sauny-po-vashemu-zhelaniyu'
      replaced_count: 1

main_page:
  afisha:
    '0':
      from: '2014-01-04 16:40'
      to: '2014-01-08 16:40'
      afisha_slug: 'postoyannaya-deystvuyuschaya-vystavka-zhivyh-tropicheskih-babochek-babochkin-dom'
    '1':
      from: '2013-12-12 19:00'
      to: '2013-12-13 19:00'
      afisha_slug: 'kulinarnyy-master-klass-merry-christmas'
  discounts:
    '0':
      from: '2014-01-15 12:30'
      to: '2015-01-16 18:30'
      discount_slug: 'podbor-sauny-po-vashemu-zhelaniyu'
