afisha:
  places:

    '1.0':
      from: '2014-03-29 10:00'
      to: '2014-04-04 21:00'
      content_type: 'afisha'
      afisha_slug: 'yumarafon-s-detmi-leytenanta-shmidta'
      replaced_count: 4

    '1.1':
      from: '2014-03-24 13:00'
      to: '2014-03-29 13:00'
      content_type: 'afisha'
      afisha_slug: 'italyanskiy-kulinarnyy-master-klass'
      replaced_count: 1

    '1.2':
      from: '2014-03-27 12:00'
      to: '2014-04-04 12:00'
      content_type: 'afisha'
      afisha_slug: 'arentinskoe-tango-dlya-novichkov-v-studii-tango-brujo'
      replaced_count: 1

    '1.4':
      from: '2014-03-21 16:00'
      to: '2015-03-21 16:00'
      content_type: 'banner'
      title: ['Школа по грудному вскармливанию']
      image: ['http://storage.znaigorod.ru/files/110860/180-320/shkola_mam.jpg']
      link: ['http://profilaktika.tomsk.ru/?p=2333']
      width: 178
      height: 320

    #'1.6':
      #from: '2014-03-28 17:00'
      #to: '2014-12-31 17:00'
      #content_type: 'review'
      #review_slug: '5-mest-tomska-gde-vesnoy-mozhno-vstretit-sportivnyh-devushek'
      #replaced_count: 2

discount:
  places:
    '1.0':
      from: '2014-01-15 12:30'
      to: '2015-01-16 18:30'
      content_type: 'discount'
      discount_slug: 'podbor-sauny-po-vashemu-zhelaniyu'
      replaced_count: 1
    '1.1':
      from: '2014-01-15 12:30'
      to: '2014-02-13 18:30'
      content_type: 'discount'
      discount_slug: 'kupon-na-valentinku-s-zhivoy-tropicheskoy-babochkoy'
      replaced_count: 1

main_page_afisha:
  places:
    '1.0':
      from: '2014-03-25 11:30'
      to: '2014-03-27 11:30'
      content_type: 'afisha'
      afisha_slug: 'vystavka-obrazovanie-za-rubezhom-2014'
      replaced_count: 1

    '1.1':
      from: '2014-03-20 12:00'
      to: '2014-03-21 23:00'
      content_type: 'afisha'
      afisha_slug: 'spektakl-eti-svobodnye-babochki'
      replaced_count: 1

    '1.2':
      from: '2014-03-20 12:00'
      to: '2014-03-21 23:00'
      content_type: 'afisha'
      afisha_slug: 'spektakl-dvoe-na-kachelyah'
      replaced_count: 1

    '1.3':
      from: '2014-03-21 10:00'
      to: '2014-03-22 10:00'
      content_type: 'afisha'
      afisha_slug: 'besplatnoe-probnoe-zanyatie-po-akterskomu-masterstvu'
      replaced_count: 1

    '1.5':
      from: '2014-03-01 14:00'
      to: '2014-04-01 00:00'
      content_type: 'banner'
      title: 'Реклама на футболе'
      image: 'http://storage.znaigorod.ru/files/80822/756-1129/forma_football.jpg'
      link: 'http://www.forma.sibr.ru/football.phtml?p=football&fl=19'
      width: 178
      height: 320

main_page_discounts:
  places:
    '1.0':
      from: '2014-01-15 12:30'
      to: '2015-01-16 18:30'
      content_type: 'discount'
      discount_slug: 'podbor-sauny-po-vashemu-zhelaniyu'
      replaced_count: 1
    '1.2':
      from: '2014-02-13 14:30'
      to: '2014-02-14 14:30'
      content_type: 'discount'
      discount_slug: 'rozygrysh-abonementov-na-mesyats-besplatnyh-zanyatiy-v-fitnes-tsentre-i-podarochnyh-sertifikatov'
      replaced_count: 1
    '1.3':
      from: '2014-01-15 12:30'
      to: '2014-02-13 18:30'
      content_type: 'discount'
      discount_slug: 'kupon-na-valentinku-s-zhivoy-tropicheskoy-babochkoy'
      replaced_count: 1

