afisha:
  places:

    '1.0':
      from: '2014-03-06 11:00'
      to: '2014-03-18 11:00'
      content_type: 'afisha'
      afisha_slug: 'pitstse-rio-10-let-i-my-darim-podarki'
      replaced_count: 4

    '1.1':
      from: '2014-03-13 09:00'
      to: '2014-03-18 09:00'
      content_type: 'afisha'
      afisha_slug: 'aktsiya-puteshestvie-na-dvoih-ot-turisticheskogo-agentstva-tvoy-tur'
      replaced_count: 1

    '1.2':
      from: '2014-03-15 14:00'
      to: '2014-03-17 14:00'
      content_type: 'afisha'
      afisha_slug: 'festival-istoricheskogo-tantsa'
      replaced_count: 1

post:
  places:

    '1.3':
      from: '2013-10-30 00:00'
      to: '2014-11-11 00:00'
      content_type: 'post'
      replaced_count: 4

discount:
  places:
    '1.0':
      from: '2014-01-15 12:30'
      to: '2015-01-16 18:30'
      content_type: 'discount'
      discount_slug: 'podbor-sauny-po-vashemu-zhelaniyu'
      replaced_count: 1
    '1.1':
      from: '2014-01-15 12:30'
      to: '2014-02-13 18:30'
      content_type: 'discount'
      discount_slug: 'kupon-na-valentinku-s-zhivoy-tropicheskoy-babochkoy'
      replaced_count: 1

main_page_afisha:
  places:
    '1.0':
      from: '2014-03-05 14:00'
      to: '2014-03-06 14:00'
      content_type: 'afisha'
      afisha_slug: 'turnir-po-mortal-kombat-9'
      replaced_count: 1

    '1.1':
      from: '2014-03-05 14:00'
      to: '2014-03-09 14:00'
      content_type: 'afisha'
      afisha_slug: 'prazdnichnaya-programma-den-vesny-i-krasoty'
      replaced_count: 1

    '1.5':
      from: '2014-03-01 14:00'
      to: '2014-04-01 00:00'
      content_type: 'banner'
      title: 'Реклама на футболе'
      image: 'http://storage.znaigorod.ru/files/80822/756-1129/forma_football.jpg'
      link: 'http://www.forma.sibr.ru/football.phtml?p=football&fl=19'
      width: 180
      height: 320

main_page_discounts:
  places:
    '1.0':
      from: '2014-01-15 12:30'
      to: '2015-01-16 18:30'
      content_type: 'discount'
      discount_slug: 'podbor-sauny-po-vashemu-zhelaniyu'
      replaced_count: 1
    '1.2':
      from: '2014-02-13 14:30'
      to: '2014-02-14 14:30'
      content_type: 'discount'
      discount_slug: 'rozygrysh-abonementov-na-mesyats-besplatnyh-zanyatiy-v-fitnes-tsentre-i-podarochnyh-sertifikatov'
      replaced_count: 1
    '1.3':
      from: '2014-01-15 12:30'
      to: '2014-02-13 18:30'
      content_type: 'discount'
      discount_slug: 'kupon-na-valentinku-s-zhivoy-tropicheskoy-babochkoy'
      replaced_count: 1
