billiard:
  categories:
    - Бильярдные залы

  features:
    - vip-зал
    - wi-fi
    - аэрохоккей
    - бизнес-ланч
    - боулинг
    - винная карта
    - детское меню
    - зал для некурящих
    - кальян
    - караоке
    - коктейльная карта
    - кофейная карта
    - нарды
    - разливное пиво
    - сигарная карта
    - спортивная трансляция
    - спортивные трансляции
    - теннис
    - тир
    - фоновая музыка
    - чайная карта
    - шахматы
    - шоу программа
    - элитные чаи

  offers:
    - американский пул
    - индивидуальные тренировки
    - клубная карта
    - организация турниров
    - подарочные сертификаты
    - русский бильярд
    - снукер

car_sales_center:
  categories:
    - европейские
    - отечественные
    - японские
    - китайские
    - корейские
    - американские
    - спецтехника
    - автобусы
    - грузовые
    - мотоциклы
    - прицепы
    - водный транспорт

  features: []

  offers: []

car_wash:
  categories:
    - мойка малогабариных автомобилей
    - мойка автомобилей среднего и бизнес-класса, кроссоверов
    - мойка крупногабаритных автомобилей, джипов, минивэнов, микроавтобусов
    - мойка грузовых автомобилей и автобусов

  features:
    - зал ожидания
    - wi-fi

  offers:
    - автоматическая мойка
    - ручная мойка
    - бесконтактная мойка
    - химчистка
    - мойка двигателя
    - полировка кузова

creation:
  categories:
  features:
  offers:

culture:
  categories:
    - Библиотеки
    - Дворцы культуры
    - Музеи
    - Планетарии
    - Театры
    - Филармонии

  features:
    - кукольные представления
    - спектакли для детей

  offers: []

entertainment:
  categories:
    - Антикафе
    - Аттракционы
    - Бильярдные залы
    - Боулинг
    - Караоке
    - Кинотеатры
    - Ночные клубы
    - Оздоровительный центр
    - Пейнтбол
    - Развлекательные комплексы
    - Страйкбол
    - Стриптиз-бары

  features:
    - vip-зал
    - wi-fi
    - аэрохоккей
    - бизнес-ланч
    - боулинг
    - винная карта
    - детское меню
    - зал для некурящих
    - кальян
    - караоке
    - коктейльная карта
    - кофейная карта
    - нарды
    - разливное пиво
    - сигарная карта
    - спортивная трансляция
    - спортивные трансляции
    - теннис
    - тир
    - фоновая музыка
    - чайная карта
    - шахматы
    - шоу программа
    - элитные чаи

  offers:
    - американский пул
    - индивидуальные тренировки
    - клубная карта
    - организация турниров
    - подарочные сертификаты
    - русский бильярд
    - снукер

meal:
  categories:
    - Банкетные залы
    - Бары
    - Детские кафе
    - Доставка еды
    - Заведения быстрого питания
    - Кафе
    - Кейтеринг
    - Кондитерские
    - Кофейни
    - Пиццерии
    - Рестораны
    - Столовые
    - Суши-бары
    - Чайная

  cuisines:
    - Авторская
    - Азиатская
    - Американская
    - Арабская
    - Восточная
    - Вьетнамская
    - Гавайская
    - Грузинская
    - Европейская
    - Ирландская
    - Итальянская
    - Кавказская
    - Китайская
    - Корейская
    - Мексиканская
    - Русская
    - Сибирская
    - Славянская
    - Тайская
    - Татарская
    - Турецкая
    - Узбекская
    - Японская

  features:
    - chill out
    - vip-зал
    - wi-fi
    - x-box
    - бильярд
    - блюда на вынос
    - боулинг
    - вегетарианское меню
    - винная карта
    - гриль-меню
    - дартц
    - детское меню
    - доставка пиццы
    - живая музыка
    - зал для некурящих
    - кальян
    - караоке
    - коктейльная карта
    - кофейная карта
    - летняя веранда
    - нарды
    - настольный футбол
    - разливное пиво
    - сигарная карта
    - спортивные трансляции
    - фоновая музыка
    - чайная карта
    - шахматы
    - шашки
    - шоу программа
    - элитные чаи
  offers:
    - банкеты
    - бизнес-ланч
    - выездное обслуживание
    - завтраки
    - закрытые вечеринки
    - корпоративные вечера
    - поминальные обеды
    - свадьбы
    - свежая выпечка
    - торжества
    - фуршеты
    - чайные церемонии
    - юбилеи

sauna:
  categories:
    - Сауны

  features:
    - wi-fi
    - бассейн
    - бильярд
    - бильярдная
    - кабельное тв
    - кальян
    - караоке
    - нарды
    - финская парная

  offers:
    - баня
    - инфракрасная парная
    - кедровая фитопаробочка
    - русская парная
    - русско-турецкая баня
    - турецкая парная
    - финская парная

sport:
  categories:
  features:
  offers:
