billiard:
  categories:
    - Бильярдные залы

  features:
    - vip-зал
    - wi-fi
    - аэрохоккей
    - бизнес-ланч
    - боулинг
    - винная карта
    - детское меню
    - зал для некурящих
    - кальян
    - караоке
    - коктейльная карта
    - кофейная карта
    - нарды
    - разливное пиво
    - сигарная карта
    - спортивная трансляция
    - спортивные трансляции
    - теннис
    - тир
    - фоновая музыка
    - чайная карта
    - шахматы
    - шоу программа
    - элитные чаи

  offers:
    - американский пул
    - индивидуальные тренировки
    - клубная карта
    - организация турниров
    - подарочные сертификаты
    - русский бильярд
    - снукер

salon_center:
  categories:
    - SPA-салоны
    - Визаж-студии
    - Массажные салоны
    - Ногтевые студии
    - Парикмахерские
    - Студии загара
    - Тату-салоны
    - Косметические салоны

  features: []

  offers: []

hotel:
  categories:
    - Гостиницы
    - Базы отдыха
    - Квартирные бюро

  features:
    - одноместные
    - двух местные
    - 3 и более местные
    - люкс
    - коттеджи
    - завтрак
    - автостоянка
    - кондиционер
    - сауна
    - зал конференций
    - баня
    - бассеин
    - спутниковое телевидение
    - настольные игры
    - Wi-Fi
    - банкетный зал
    - бильярд
    - мангал
    - летняя веранда

  offers:
    - аренда автомобиля
    - прокат снегоходов
    - прокат лодок
    - прокат квадрациклов
    - прокат катамаранов
    - массаж
    - проведение конференций

travel:
  categories:
    - Туристические агентства
    - Билетные сервисы

  features:
    - услуги для поездок по России
    - услуги для поездок зарубеж

  offers:
    - горячие путевки
    - автобусные туры
    - экскурсионные туры
    - ранее бронирование
    - круизы
    - свадебные путешествия
    - лечебные туры
    - шоп-туры
    - событийные туры

car_service_center:
  categories: []

  features: []

  offers:
    - кузовной ремонт
    - электрика
    - ремонт двигателя
    - ремонт ходовой части
    - тюнинг
    - мелкосрочный ремонт
    - шиномонтаж
    - ремонт коробки передач
    - автостекла
    - ТО

car_sales_center:
  categories:
    - Легковые автомобили
    - Грузовые и спецтехника
    - Мототехника
    - Водный транспорт

  features:
    - новые
    - с пробегом

  offers:
    - кредит
    - лизинг
    - рассрочка
    - сервисное обслуживание
    - продажа запчастей

car_wash:
  categories:
    - Автомойки

  features:
    - зал ожидания
    - wi-fi

  offers:
    - мойка малогабариных автомобилей
    - мойка автомобилей среднего и бизнес-класса/кроссоверов
    - мойка крупногабаритных автомобилей/джипов/минивэнов/микроавтобусов
    - мойка грузовых автомобилей и автобусов
    - автоматическая мойка
    - ручная мойка
    - бесконтактная мойка
    - химчистка салона
    - мойка двигателя
    - полировка кузова

creation:
  categories:
  features:
  offers:

culture:
  categories:
    - Библиотеки
    - Дворцы культуры
    - Музеи
    - Планетарии
    - Театры
    - Филармонии

  features:
    - кукольные представления
    - спектакли для детей

  offers: []

entertainment:
  categories:
    - Антикафе
    - Аттракционы
    - Бильярдные залы
    - Боулинг
    - Караоке
    - Кинотеатры
    - Ночные клубы
    - Оздоровительный центр
    - Пейнтбол
    - Развлекательные комплексы
    - Страйкбол
    - Стриптиз-бары

  features:
    - vip-зал
    - wi-fi
    - аэрохоккей
    - бизнес-ланч
    - боулинг
    - винная карта
    - детское меню
    - зал для некурящих
    - кальян
    - караоке
    - коктейльная карта
    - кофейная карта
    - нарды
    - разливное пиво
    - сигарная карта
    - спортивная трансляция
    - спортивные трансляции
    - теннис
    - тир
    - фоновая музыка
    - чайная карта
    - шахматы
    - шоу программа
    - элитные чаи

  offers:
    - американский пул
    - индивидуальные тренировки
    - клубная карта
    - организация турниров
    - подарочные сертификаты
    - русский бильярд
    - снукер

meal:
  categories:
    - Банкетные залы
    - Бары
    - Детские кафе
    - Доставка еды
    - Заведения быстрого питания
    - Кафе
    - Кейтеринг
    - Кондитерские
    - Кофейни
    - Пиццерии
    - Рестораны
    - Столовые
    - Суши-бары
    - Чайная

  cuisines:
    - Авторская
    - Азиатская
    - Американская
    - Арабская
    - Восточная
    - Вьетнамская
    - Гавайская
    - Грузинская
    - Европейская
    - Ирландская
    - Итальянская
    - Кавказская
    - Китайская
    - Корейская
    - Мексиканская
    - Русская
    - Сибирская
    - Славянская
    - Тайская
    - Татарская
    - Турецкая
    - Узбекская
    - Японская

  features:
    - chill out
    - vip-зал
    - wi-fi
    - x-box
    - бильярд
    - блюда на вынос
    - боулинг
    - вегетарианское меню
    - винная карта
    - гриль-меню
    - дартц
    - детское меню
    - доставка пиццы
    - живая музыка
    - зал для некурящих
    - кальян
    - караоке
    - коктейльная карта
    - кофейная карта
    - летняя веранда
    - нарды
    - настольный футбол
    - разливное пиво
    - сигарная карта
    - спортивные трансляции
    - фоновая музыка
    - чайная карта
    - шахматы
    - шашки
    - шоу программа
    - элитные чаи
  offers:
    - банкеты
    - бизнес-ланч
    - выездное обслуживание
    - завтраки
    - закрытые вечеринки
    - корпоративные вечера
    - поминальные обеды
    - свадьбы
    - свежая выпечка
    - торжества
    - фуршеты
    - чайные церемонии
    - юбилеи

sauna:
  categories:
    - Сауны

  features:
    - wi-fi
    - бассейн
    - бильярд
    - бильярдная
    - кабельное тв
    - кальян
    - караоке
    - нарды
    - финская парная

  offers:
    - баня
    - инфракрасная парная
    - кедровая фитопаробочка
    - русская парная
    - русско-турецкая баня
    - турецкая парная
    - финская парная

sport:
  categories:
  features:
  offers:
